"""empty message

Revision ID: 177b02f8bc2c
Revises: 
Create Date: 2019-12-08 16:11:07.678446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177b02f8bc2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
